script: bundle exec rspec spec
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
before_install:
  - gem install bundler -v 1.9.3
  - gem install mime-types -v 2.6.2
  - gem update --system
  - gem --version
